# Generated by Django 5.1 on 2024-09-27 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='name',
            new_name='content',
        ),
    ]
